services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.${APP_ENV}
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - /app/backend/node_modules
      - /app/frontend/node_modules
