sonar.projectKey=Eletronjun_dog-video
sonar.organization=eletronjun

sonar.projectName=DogVideo
sonar.projectVersion=1.0

# Paths to analyze
sonar.sources=backend,frontend

# Exclude test files, modules, tokens, build and config from analysis
sonar.exclusions=**/node_modules/**,**/tests/**,**/coverage/**,**/*.test.js,**/jest.config.js,**/config/**,backend/tokens/**,frontend/build/**,**/public/sw.js

# Exclude standalone scripts and entrypoints from coverage calculations
sonar.coverage.exclusions=backend/gerar_token.js,backend/server/**,backend/link_live.js,backend/scripts/**,backend/vapidkey.js,frontend/src/reportWebVitals.js,frontend/src/index.js,**/node_modules/**,**/tests/**,**/coverage/**,**/*.test.js

# Coverage paths
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
